name: 'Setup'
description: 'Setup debug, Node.js, and pnpm with caching'

# Dependencies:
#   - actions/setup-node@v5.0.0
#   - pnpm/action-setup@v4.1.0
#   - SocketDev/socket-registry/.github/actions/debug

inputs:
  debug:
    description: 'Enable debug output'
    required: false
    default: '0'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '^10.16.0'
  scope:
    description: 'npm registry scope for package authentication'
    required: false
    default: ''
  registry-url:
    description: 'npm registry URL'
    required: false
    default: 'https://registry.npmjs.org'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup debug
      uses: SocketDev/socket-registry/.github/actions/debug@51be85d39d3b4a42dd9d4712948b9d30a2e04794 # main
      with:
        debug: ${{ inputs.debug }}

    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js with pnpm cache
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.working-directory != '.' && format('{0}/pnpm-lock.yaml', inputs.working-directory) || 'pnpm-lock.yaml' }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
