name: 'Setup'
description: 'Setup Node.js and pnpm with caching'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '^10.16.0'
  scope:
    description: 'NPM registry scope for package authentication'
    required: false
    default: ''
  registry-url:
    description: 'NPM registry URL'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js with pnpm cache
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}

    - name: Install dependencies
      shell: bash
      run: |
        pnpm add -g @socketsecurity/cli
        alias pnpm='socket-pnpm'
        export SOCKET_CLI_CONFIG='{"issueRules":{"malware":true,"gptMalware":true}}'
        pnpm install
