packages:
  - packages/npm/*
  - perf/*
  - registry
  - scripts
catalog:
  '@babel/core': 7.28.4
  '@babel/generator': 7.28.3
  '@babel/parser': 7.28.4
  '@babel/traverse': 7.28.4
  '@babel/types': 7.28.4
  '@biomejs/biome': 2.2.4
  '@biomejs/wasm-nodejs': 2.2.4
  '@socketregistry/packageurl-js': 1.3.5
  '@socketsecurity/lib': 3.2.4
  '@types/node': 24.9.2
  '@vitest/coverage-v8': 4.0.3
  '@vitest/ui': 4.0.3
  del: 8.0.1
  del-cli: 6.0.0
  esbuild: 0.25.11
  eslint: 9.35.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-n: 17.23.1
  eslint-plugin-sort-destructure-keys: 2.0.0
  eslint-plugin-unicorn: 56.0.1
  fast-glob: 3.3.3
  husky: 9.1.7
  magic-string: 0.30.17
  normalize-package-data: 8.0.0
  npm-package-arg: 13.0.0
  pacote: 21.0.1
  semver: 7.7.2
  typescript: 5.9.2
  typescript-eslint: 8.44.1
  validate-npm-package-name: 6.0.2
  vitest: 4.0.3
  yoctocolors-cjs: 2.1.3
  zod: 4.1.12
  '@biomejs/js-api': 3.0.0
  '@eslint/compat': 1.4.1
  '@eslint/js': 9.35.0
  '@inquirer/checkbox': 4.2.4
  '@inquirer/core': 10.2.2
  '@inquirer/prompts': 7.8.6
  '@mdn/browser-compat-data': 7.1.5
  '@npmcli/package-json': 7.0.0
  '@npmcli/promise-spawn': 8.0.3
  '@types/fs-extra': 11.0.4
  '@types/normalize-package-data': 2.4.4
  '@types/npm-package-arg': 6.1.4
  '@types/npmcli__package-json': 4.0.4
  '@types/npmcli__promise-spawn': 6.0.3
  '@types/picomatch': 4.0.2
  '@types/semver': 7.7.1
  '@types/spdx-correct': 3.1.3
  '@types/spdx-expression-parse': 3.0.5
  '@types/validate-npm-package-name': 4.0.2
  '@types/which': 3.0.4
  '@typescript/native-preview': 7.0.0-dev.20250920.1
  '@yarnpkg/extensions': 2.0.6
  '@zkochan/js-yaml': 0.0.10
  brace-expansion: 2.0.2
  browserslist: 4.26.3
  c8: 10.1.3
  cacache: 20.0.1
  clipboardy: 4.0.0
  debug: ^4.4.3
  dev-null-cli: 2.0.0
  didyoumean2: 7.0.4
  eslint-import-resolver-typescript: 4.4.4
  eta: 3.5.0
  fast-sort: 3.4.1
  fs-extra: 11.3.1
  get-east-asian-width: 1.3.0
  globals: 16.4.0
  iconv-lite: 0.6.3
  js-yaml: npm:@zkochan/js-yaml@0.0.10
  libnpmpack: 9.0.9
  make-fetch-happen: 15.0.2
  minimatch: 9.0.5
  out-url: 1.2.2
  read-yaml-file: 2.1.0
  source-map-support: 0.5.21
  spdx-correct: 3.2.0
  spdx-expression-parse: 4.0.0
  streaming-iterables: 8.0.1
  tar: 7.5.1
  taze: 19.6.0
  trash: 10.0.0
  tsx: 4.20.5
  type-coverage: 2.29.7
  update-browserslist-db: 1.1.3
  vite: 7.1.12
  which: 5.0.0
  yargs-parser: 22.0.0
patchedDependencies:
  brace-expansion@2.0.2: patches/brace-expansion@2.0.2.patch
  iconv-lite@0.6.3: patches/iconv-lite@0.6.3.patch
  minimatch@9.0.5: patches/minimatch@9.0.5.patch
