packages:
  - packages/npm/*
  - perf/*
  - registry
  - scripts

catalog:
  '@babel/core': 7.28.4
  '@babel/generator': 7.28.3
  '@babel/parser': 7.28.4
  '@babel/traverse': 7.28.4
  '@babel/types': 7.28.4
  '@biomejs/biome': 2.2.4
  '@biomejs/wasm-nodejs': 2.2.4
  '@socketregistry/packageurl-js': 1.3.5
  '@socketsecurity/lib': 3.2.1
  '@types/node': 24.9.2
  '@vitest/coverage-v8': 4.0.3
  '@vitest/ui': 4.0.3
  del: 8.0.1
  del-cli: 6.0.0
  esbuild: 0.25.11
  eslint: 9.35.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-n: 17.23.1
  eslint-plugin-sort-destructure-keys: 2.0.0
  eslint-plugin-unicorn: 56.0.1
  fast-glob: 3.3.3
  husky: 9.1.7
  magic-string: 0.30.21
  normalize-package-data: 8.0.0
  npm-package-arg: 13.0.0
  pacote: 21.0.1
  semver: 7.7.2
  typescript: 5.9.2
  typescript-eslint: 8.44.1
  validate-npm-package-name: 6.0.2
  vitest: 4.0.3
  yoctocolors-cjs: 2.1.3
  zod: 4.1.12

patchedDependencies:
  brace-expansion@2.0.2: patches/brace-expansion@2.0.2.patch
  iconv-lite@0.6.3: patches/iconv-lite@0.6.3.patch
  minimatch@9.0.5: patches/minimatch@9.0.5.patch
