export declare const CHANGELOG_MD: string
export declare const DOT_GITHUB: string
export declare const ESLINT_CONFIG_JS: string
export declare const EXTENSIONS_JSON: string
export declare const LICENSE: string
export declare const MANIFEST_JSON: string
export declare const NODE_MODULES: string
export declare const PACKAGE_JSON: string
export declare const PACKAGE_LOCK_JSON: string
export declare const PNPM_LOCK_YAML: string
export declare const README_MD: string
export declare const TSCONFIG_JSON: string
export declare const YARN_LOCK: string
export declare const ROOT_PATH: string
export declare const NPM: string
export declare const PNPM: string
export declare const YARN: string
export declare const REGISTRY: string
export declare const SOCKET_REGISTRY_SCOPE: string
export declare const ROOT_NODE_MODULES_PATH: string
export declare const ROOT_NODE_MODULES_BIN_PATH: string
export declare const ROOT_PACKAGE_JSON_PATH: string
export declare const ROOT_PACKAGE_LOCK_PATH: string
export declare const ROOT_PACKAGES_PATH: string
export declare const ROOT_LICENSE_PATH: string
export declare const ROOT_ESLINT_CONFIG_PATH: string
export declare const ROOT_TSCONFIG_PATH: string
export declare const NPM_PACKAGES_PATH: string
export declare const REGISTRY_PKG_PATH: string
export declare const REGISTRY_MANIFEST_JSON_PATH: string
export declare const REGISTRY_EXTENSIONS_JSON_PATH: string
export declare const TEST_NPM_PATH: string
export declare const TEST_NPM_NODE_MODULES_PATH: string
export declare const TEST_NPM_PKG_JSON_PATH: string
export declare const TEST_NPM_PKG_LOCK_PATH: string
export declare const TEST_NPM_FIXTURES_PATH: string
export declare const TEST_NPM_NODE_WORKSPACES_PATH: string
export declare const REL_NPM_PACKAGES_PATH: string
export declare const REL_PACKAGES_PATH: string
export declare const REL_REGISTRY_PKG_PATH: string
export declare const REL_REGISTRY_MANIFEST_JSON_PATH: string
export declare const REL_TEST_NPM_PATH: string
export declare const REL_TEST_NPM_NODE_MODULES_PATH: string
export declare const TEMPLATES_PATH: string
export declare const NPM_TEMPLATES_PATH: string
export declare const NPM_TEMPLATES_README_PATH: string
export declare const PERF_NPM_PATH: string
export declare const PERF_NPM_FIXTURES_PATH: string
export declare const ROOT_CACHE_PATH: string
export declare const ROOT_GITHUB_CACHE_PATH: string
export declare const ROOT_DOT_GITHUB_PATH: string
export declare const ROOT_DOT_GITHUB_ACTIONS_PATH: string
export declare const ROOT_DOT_GITHUB_WORKFLOWS_PATH: string
