'use strict'

const shimIterator = require('./Iterator/shim')
const shimIteratorConcat = require('./Iterator.concat/shim')
const shimIteratorFrom = require('./Iterator.from/shim')
const shimIteratorProto = require('./Iterator.prototype/shim')
const shimIteratorProtoCtor = require('./Iterator.prototype.constructor/shim')
const shimIteratorProtoDrop = require('./Iterator.prototype.drop/shim')
const shimIteratorProtoEvery = require('./Iterator.prototype.every/shim')
const shimIteratorProtoFilter = require('./Iterator.prototype.filter/shim')
const shimIteratorProtoFind = require('./Iterator.prototype.find/shim')
const shimIteratorProtoFlatMap = require('./Iterator.prototype.flatMap/shim')
const shimIteratorProtoForEach = require('./Iterator.prototype.forEach/shim')
const shimIteratorProtoMap = require('./Iterator.prototype.map/shim')
const shimIteratorProtoReduce = require('./Iterator.prototype.reduce/shim')
const shimIteratorProtoSome = require('./Iterator.prototype.some/shim')
const shimIteratorProtoTake = require('./Iterator.prototype.take/shim')
const shimIteratorProtoToArray = require('./Iterator.prototype.toArray/shim')
const shimIteratorZip = require('./Iterator.zip/shim')
const shimIteratorZipKeyed = require('./Iterator.zipKeyed/shim')

module.exports = function shimIteratorHelpers() {
  shimIterator()
  shimIteratorProto()
  shimIteratorConcat()
  shimIteratorFrom()
  shimIteratorZip()
  shimIteratorZipKeyed()
  shimIteratorProtoCtor()
  shimIteratorProtoDrop()
  shimIteratorProtoEvery()
  shimIteratorProtoFilter()
  shimIteratorProtoFind()
  shimIteratorProtoFlatMap()
  shimIteratorProtoForEach()
  shimIteratorProtoMap()
  shimIteratorProtoReduce()
  shimIteratorProtoSome()
  shimIteratorProtoTake()
  shimIteratorProtoToArray()
}
