/**
 * Static constants that don't require any runtime computation or dependencies.
 * These are safe to bundle and won't cause circular dependencies.
 */

// File and directory names.
export const AT_LATEST = '@latest'
export const BUN = 'bun'
export const BUN_LOCK = 'bun.lock'
export const BUN_LOCKB = 'bun.lockb'
export const CACHE_DIR = 'cache'
export const CACHE_GITHUB_DIR = 'github'
export const CACHE_SOCKET_API_DIR = 'socket-api'
export const CACHE_TTL_DIR = 'ttl'
export const CHANGELOG_MD = 'CHANGELOG.md'
export const CI = 'CI'
export const COLUMN_LIMIT = 80
export const DOT_GIT_DIR = '.git'
export const DOT_GITHUB = '.github'
export const DOT_PACKAGE_LOCK_JSON = '.package-lock.json'
export const DOT_SOCKET_DIR = '.socket'
export const EMPTY_FILE = '/* empty */\n'
export const EMPTY_VALUE = '<value>'
export const ESLINT_CONFIG_JS = 'eslint.config.js'
export const ESNEXT = 'esnext'
export const EXT_CJS = '.cjs'
export const EXT_CMD = '.cmd'
export const EXT_CTS = '.cts'
export const EXT_DTS = '.d.ts'
export const EXT_JS = '.js'
export const EXT_JSON = '.json'
export const EXT_LOCK = '.lock'
export const EXT_LOCKB = '.lockb'
export const EXT_MD = '.md'
export const EXT_MJS = '.mjs'
export const EXT_MTS = '.mts'
export const EXT_PS1 = '.ps1'
export const EXT_YAML = '.yaml'
export const EXT_YML = '.yml'
export const EXTENSIONS = 'extensions'
export const EXTENSIONS_JSON = 'extensions.json'
export const GITIGNORE = '.gitignore'
export const GITHUB_API_BASE_URL = 'https://api.github.com'
export const LATEST = 'latest'
export const LICENSE = 'LICENSE'
export const LICENSE_GLOB = 'LICEN[CS]E{[.-]*,}'
export const LICENSE_GLOB_RECURSIVE = '**/LICEN[CS]E{[.-]*,}'
export const LICENSE_ORIGINAL = 'LICENSE.original'
export const LICENSE_ORIGINAL_GLOB = '*.original{.*,}'
export const LICENSE_ORIGINAL_GLOB_RECURSIVE = '**/*.original{.*,}'
export const LICENSE_MD = 'LICENSE.md'
export const LOOP_SENTINEL = 1_000_000
export const MANIFEST_JSON = 'manifest.json'
export const MIT = 'MIT'
export const NODE_AUTH_TOKEN = 'NODE_AUTH_TOKEN'
export const NODE_ENV = 'NODE_ENV'
export const NODE_MODULES = 'node_modules'
export const NODE_MODULES_GLOB_RECURSIVE = '**/node_modules'
export const NODE_SEA_FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2'
export const NPM = 'npm'
export const NPM_SHRINKWRAP_JSON = 'npm-shrinkwrap.json'
export const NPX = 'npx'
export const OVERRIDES = 'overrides'
export const PACKAGE = 'package'
export const PACKAGE_DEFAULT_VERSION = '1.0.0'
export const PACKAGE_JSON = 'package.json'
export const PACKAGE_LOCK = 'package-lock'
export const PACKAGE_LOCK_JSON = 'package-lock.json'
export const PNPM = 'pnpm'
export const PNPM_LOCK = 'pnpm-lock'
export const PNPM_LOCK_YAML = 'pnpm-lock.yaml'
export const PNPM_WORKSPACE_YAML = 'pnpm-workspace.yaml'
export const PRE_COMMIT = 'PRE_COMMIT'
export const README_GLOB = 'README{.*,}'
export const README_GLOB_RECURSIVE = '**/README{.*,}'
export const README_MD = 'README.md'
export const REGISTRY = 'registry'
export const REGISTRY_SCOPE_DELIMITER = '__'
export const RESOLUTIONS = 'resolutions'
export const SLASH_NODE_MODULES_SLASH = '/node_modules/'
export const SOCKET_API_BASE_URL = 'https://api.socket.dev/v0'
export const SOCKET_APP_PREFIX = '_'
export const SOCKET_CLI_APP_NAME = 'socket'
export const SOCKET_DLX_APP_NAME = 'dlx'
export const SOCKET_FIREWALL_APP_NAME = 'sfw'
export const SOCKET_GITHUB_ORG = 'SocketDev'
export const SOCKET_IPC_HANDSHAKE = 'SOCKET_IPC_HANDSHAKE'
export const SOCKET_OVERRIDE_SCOPE = '@socketoverride'
export const SOCKET_PUBLIC_API_KEY = 'sktsec_t_--RAN5U4ivauy4w37-6aoKyYPDt5ZbaT5JBVMqiwKo_api'
export const SOCKET_PUBLIC_API_TOKEN = SOCKET_PUBLIC_API_KEY // Alias for backward compatibility.
export const SOCKET_REGISTRY_APP_NAME = 'registry'
export const SOCKET_REGISTRY_NPM_ORG = 'socketregistry'
export const SOCKET_REGISTRY_PACKAGE_NAME = '@socketsecurity/registry'
export const SOCKET_REGISTRY_REPO_NAME = 'socket-registry'
export const SOCKET_REGISTRY_SCOPE = '@socketregistry'
export const SOCKET_SECURITY_SCOPE = '@socketsecurity'
export const TEST = 'test'
export const TSCONFIG_JSON = 'tsconfig.json'
export const UNDEFINED_TOKEN = undefined
export const UNKNOWN_ERROR = 'Unknown error'
export const UNKNOWN_VALUE = '<unknown>'
export const UNLICENCED = 'UNLICENCED'
export const UNLICENSED = 'UNLICENSED'
export const UTF8 = 'utf8'
export const V = 'v'
export const VITEST = 'VITEST'
export const VLT = 'vlt'
export const VLT_LOCK_JSON = 'vlt-lock.json'
export const YARN = 'yarn'
export const YARN_BERRY = 'yarn/berry'
export const YARN_CLASSIC = 'yarn/classic'
export const YARN_LOCK = 'yarn.lock'

// Character codes.
export const CHAR_BACKWARD_SLASH = 92
export const CHAR_COLON = 58
export const CHAR_FORWARD_SLASH = 47
export const CHAR_LOWERCASE_A = 97
export const CHAR_LOWERCASE_Z = 122
export const CHAR_UPPERCASE_A = 65
export const CHAR_UPPERCASE_Z = 90

// Stat mode constants.
export const S_IXGRP = 0o010
export const S_IXOTH = 0o001
export const S_IXUSR = 0o100

// Rollup external suffix.
export const ROLLUP_EXTERNAL_SUFFIX = '__rollup_external'