name: 'Setup and Install'
description: 'Complete setup including checkout, debug, Node.js, cache, and dependency installation'

inputs:
  checkout:
    description: 'Whether to checkout code'
    required: false
    default: 'true'
  checkout-ref:
    description: 'Git ref to checkout'
    required: false
    default: ''
  debug:
    description: 'Enable debug output'
    required: false
    default: '0'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'


runs:
  using: 'composite'
  steps:
    - name: Checkout code
      if: inputs.checkout == 'true'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ inputs.checkout-ref }}

    - name: Setup debug
      uses: SocketDev/socket-registry/.github/actions/debug@main
      with:
        debug: ${{ inputs.debug }}

    - name: Setup Node.js
      uses: SocketDev/socket-registry/.github/actions/setup@main
      with:
        node-version: ${{ inputs.node-version }}