name: 'Setup and Install'
description: 'Checkout code, setup environment, and install dependencies'

# Dependencies:
#   - actions/checkout@v5.0.0
#   - SocketDev/socket-registry/.github/actions/setup
#     - SocketDev/socket-registry/.github/actions/debug
#     - pnpm/action-setup@v4.1.0
#     - actions/setup-node@v5.0.0
#   - SocketDev/socket-registry/.github/actions/install

inputs:
  checkout:
    description: 'Whether to checkout code'
    required: false
    default: 'true'
  checkout-ref:
    description: 'Git ref to checkout'
    required: false
    default: ''
  debug:
    description: 'Enable debug output'
    required: false
    default: '0'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '10.16.0'
  scope:
    description: 'npm registry scope for package authentication'
    required: false
    default: ''
  registry-url:
    description: 'npm registry URL'
    required: false
    default: 'https://registry.npmjs.org'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      if: inputs.checkout == 'true'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ inputs.checkout-ref }}
        path: ${{ inputs.working-directory != '.' && inputs.working-directory || '' }}
        fetch-depth: 100

    - name: Setup environment
      uses: SocketDev/socket-registry/.github/actions/setup@51be85d39d3b4a42dd9d4712948b9d30a2e04794 # main
      with:
        debug: ${{ inputs.debug }}
        node-version: ${{ inputs.node-version }}
        pnpm-version: ${{ inputs.pnpm-version }}
        scope: ${{ inputs.scope }}
        registry-url: ${{ inputs.registry-url }}
        working-directory: ${{ inputs.working-directory }}

    - name: Install dependencies
      uses: SocketDev/socket-registry/.github/actions/install@51be85d39d3b4a42dd9d4712948b9d30a2e04794 # main
      with:
        working-directory: ${{ inputs.working-directory }}
