/**
 * @fileoverview Downloads the sfw-free binary and injects a pnpm shim into
 * GITHUB_PATH so every subsequent `pnpm` invocation in the job is transparently
 * wrapped by `sfw`. Must run before any `pnpm install` step.
 *
 * Usage (GitHub Actions composite step):
 *   shell: bash
 *   run: node "${{ github.action_path }}/setup-sfw.mjs"
 */

import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import https from 'node:https'
import os from 'node:os'
import path from 'node:path'
import process from 'node:process'

// Platform → sfw release artifact name.
const PLATFORM_MAP = {
  __proto__: null,
  'darwin-arm64': 'sfw-darwin-arm64',
  'darwin-x64': 'sfw-darwin-x86_64',
  'linux-arm64': 'sfw-linux-arm64',
  'linux-x64': 'sfw-linux-x86_64',
  'win32-x64': 'sfw-windows-amd64.exe',
}

const WIN32 = process.platform === 'win32'
const platformKey = `${process.platform}-${process.arch}`
const artifactName = PLATFORM_MAP[platformKey]

if (!artifactName) {
  process.stderr.write(`Unsupported platform/arch: ${platformKey}\n`)
  process.exitCode = 1
  throw new Error(`unsupported platform "${platformKey}"`)
}

/**
 * Follow redirects and download a URL to a destination file path.
 * @param {string} url
 * @param {string} dest
 * @returns {Promise<void>}
 */
function download(url, dest) {
  return new Promise((resolve, reject) => {
    const request = currentUrl => {
      https
        .get(currentUrl, res => {
          if (
            res.statusCode >= 300 &&
            res.statusCode < 400 &&
            res.headers.location
          ) {
            request(res.headers.location)
            return
          }
          if (res.statusCode !== 200) {
            reject(new Error(`download failed with status ${res.statusCode}`))
            return
          }
          const out = fs.createWriteStream(dest)
          res.pipe(out)
          out.on('finish', resolve)
          out.on('error', reject)
        })
        .on('error', reject)
    }
    request(url)
  })
}

async function main() {
  const sfwUrl = `https://github.com/SocketDev/sfw-free/releases/latest/download/${artifactName}`

  // Use a stable per-job dir under the runner's temp path so the shim dir
  // survives across steps. Fall back to os.tmpdir() outside GitHub Actions.
  const baseDir = process.env['RUNNER_TEMP'] ?? os.tmpdir()
  const shimDir = path.join(baseDir, 'sfw-shim')
  fs.mkdirSync(shimDir, { recursive: true })

  const sfwBin = WIN32
    ? path.join(shimDir, 'sfw.exe')
    : path.join(shimDir, 'sfw')

  process.stdout.write(`Downloading sfw from ${sfwUrl}\n`)
  await download(sfwUrl, sfwBin)

  if (!WIN32) {
    fs.chmodSync(sfwBin, 0o755)
  }

  // Write a pnpm shim that forwards all args through sfw.
  // shell: WIN32 is the canonical cross-platform pattern — enables shell on
  // Windows only, where it is required to resolve .exe and PATH correctly.
  const shimScript = path.join(shimDir, 'pnpm-shim.mjs')
  const shimContent =
    [
      `// Auto-generated by .github/actions/install/setup-sfw.mjs — do not edit.`,
      `import { spawnSync } from 'node:child_process'`,
      `import process from 'node:process'`,
      `const result = spawnSync(`,
      `  ${JSON.stringify(sfwBin)},`,
      `  ['pnpm', ...process.argv.slice(2)],`,
      `  { stdio: 'inherit', shell: ${WIN32} }`,
      `)`,
      `process.exitCode = result.status ?? 1`,
    ].join('\n') + '\n'

  fs.writeFileSync(shimScript, shimContent, 'utf8')

  if (WIN32) {
    // .cmd shim so Windows PATH resolution finds "pnpm" → runs node shimScript.
    const cmdShim = path.join(shimDir, 'pnpm.cmd')
    fs.writeFileSync(cmdShim, `@node "${shimScript}" %*\r\n`, 'utf8')
  } else {
    // On POSIX, write a wrapper script named "pnpm" that calls node on the shim.
    // Avoids shebang dependency — the shell invokes node explicitly.
    const posixShim = path.join(shimDir, 'pnpm')
    fs.writeFileSync(posixShim, `node "${shimScript}" "$@"\n`, 'utf8')
    fs.chmodSync(posixShim, 0o755)
  }

  // Prepend shimDir to GITHUB_PATH so subsequent steps resolve our shim first.
  const githubPath = process.env['GITHUB_PATH']
  if (githubPath) {
    fs.appendFileSync(githubPath, `${shimDir}\n`, 'utf8')
    process.stdout.write(`Added ${shimDir} to GITHUB_PATH\n`)
  } else {
    // Outside of GitHub Actions — warn but don't fail.
    process.stderr.write(
      `GITHUB_PATH not set — shim installed at ${shimDir} but not added to PATH\n`,
    )
  }

  // Verify the shim files were written correctly.
  const shimFile = WIN32 ? path.join(shimDir, 'pnpm.cmd') : path.join(shimDir, 'pnpm')
  if (!fs.existsSync(shimFile)) {
    throw new Error(`pnpm shim not found at ${shimFile}`)
  }
  if (!fs.existsSync(sfwBin)) {
    throw new Error(`sfw binary not found at ${sfwBin}`)
  }

  process.stdout.write(`sfw pnpm shim ready at ${shimDir}\n`)
}

main().catch(e => {
  process.stderr.write(`setup-sfw failed: ${e.message}\n`)
  process.exitCode = 1
})
