#!/usr/bin/env node
/*
 * @file Generates docs/agents.md/repo/npm-high-impact-rankings.md from the
 *   catalog-pinned npm-high-impact dataset. Every packages/npm override is
 *   ranked by its position in `npmHighImpact` (downloads-first union list),
 *   `npmTopDownloads`, and `npmTopDependents`; the doc's headline stats and
 *   tables are all derived, never hand-maintained. Deterministic given the
 *   dataset version, so the companion check
 *   (scripts/repo/check/npm-rankings-doc-is-current.mts) can byte-compare the
 *   committed doc and fail CI when a dependency bump makes it stale. Run:
 *   node scripts/repo/npm/gen-high-impact-rankings.mts [--write]
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { resolveOriginalPackageName } from '@socketsecurity/lib-stable/packages/normalize'

import { isMainModule } from '../../fleet/_shared/is-main-module.mts'
import { NPM_PACKAGES_PATH, ROOT_PATH } from '../constants/paths.mts'

const logger = getDefaultLogger()

export const RANKINGS_DOC_PATH = path.join(
  ROOT_PATH,
  'docs',
  'agents.md',
  'repo',
  'npm-high-impact-rankings.md',
)

export interface OverrideRanking {
  dependentsRank: number | undefined
  downloadsRank: number | undefined
  impactRank: number | undefined
  name: string
}

interface HighImpactData {
  npmHighImpact: readonly string[]
  npmTopDependents: readonly string[]
  npmTopDownloads: readonly string[]
  version: string
}

async function loadHighImpactData(): Promise<HighImpactData> {
  const mod = await import('npm-high-impact')
  const manifest = JSON.parse(
    readFileSync(
      path.join(ROOT_PATH, 'node_modules', 'npm-high-impact', 'package.json'),
      'utf8',
    ),
  ) as { version: string }
  return {
    npmHighImpact: mod.npmHighImpact,
    npmTopDependents: mod.npmTopDependents,
    npmTopDownloads: mod.npmTopDownloads,
    version: manifest.version,
  }
}

function rankMap(list: readonly string[]): Map<string, number> {
  const map = new Map<string, number>()
  for (let i = 0, { length } = list; i < length; i += 1) {
    const name = list[i]
    if (name !== undefined && !map.has(name)) {
      map.set(name, i + 1)
    }
  }
  return map
}

export function collectOverrideRankings(
  data: Pick<
    HighImpactData,
    'npmHighImpact' | 'npmTopDependents' | 'npmTopDownloads'
  >,
  overrideNames: readonly string[],
): OverrideRanking[] {
  const impact = rankMap(data.npmHighImpact)
  const downloads = rankMap(data.npmTopDownloads)
  const dependents = rankMap(data.npmTopDependents)
  const rows: OverrideRanking[] = []
  for (const name of overrideNames) {
    rows.push({
      dependentsRank: dependents.get(name),
      downloadsRank: downloads.get(name),
      impactRank: impact.get(name),
      name,
    })
  }
  return rows
}

function formatCell(rank: number | undefined): string {
  return rank === undefined ? '-' : String(rank)
}

export function renderHighImpactRankings(
  data: HighImpactData,
  overrideNames: readonly string[],
): string {
  const rows = collectOverrideRankings(data, overrideNames)
  const listed = rows
    .filter(r => r.impactRank !== undefined)
    .toSorted((a, b) => (a.impactRank ?? 0) - (b.impactRank ?? 0))
  const total = rows.length
  const top100 = listed.filter(r => (r.impactRank ?? Infinity) <= 100).length
  const top500 = listed.filter(r => (r.impactRank ?? Infinity) <= 500).length
  const top1000 = listed.filter(r => (r.impactRank ?? Infinity) <= 1000).length
  const viaDownloads = listed.filter(
    r => r.impactRank === r.downloadsRank,
  ).length
  const inDependents = listed.filter(r => r.dependentsRank !== undefined)
  const highest = listed[0]
  const byDependents = inDependents.toSorted(
    (a, b) => (a.dependentsRank ?? 0) - (b.dependentsRank ?? 0),
  )
  const pct = ((listed.length / total) * 100).toFixed(1)
  const highestPct = highest?.impactRank
    ? ((highest.impactRank / data.npmHighImpact.length) * 100).toFixed(1)
    : '?'

  const lines = [
    '# packages/npm overrides ranked by npm-high-impact',
    '',
    `Generated by \`scripts/repo/npm/gen-high-impact-rankings.mts\` from`,
    `npm-high-impact ${data.version} (workspace devDependency, catalog-pinned);`,
    'do not hand-edit. The package publishes three lists: `npmHighImpact`',
    `(${data.npmHighImpact.length.toLocaleString('en-US')} packages, the union of the two lists below with the`,
    'downloads-ranked portion first), `npmTopDownloads`',
    `(${data.npmTopDownloads.length.toLocaleString('en-US')} packages by weekly downloads), and \`npmTopDependents\``,
    `(${data.npmTopDependents.length.toLocaleString('en-US')} packages by dependent count, sourced from ecosyste.ms).`,
    '',
    'Method: each `packages/npm/<dir>` directory names the upstream package it',
    "overrides (`scope__name` maps to `@scope/name`); rank is the package's",
    '1-based position in each list.',
    '',
    '## Headline',
    '',
    `- ${listed.length} of ${total} overrides (${pct}%) appear in \`npmHighImpact\`.`,
    `- ${top100} rank in the top 100, ${top500} in the top 500, and ${top1000} in the`,
    `  top 1,000 of the ${data.npmHighImpact.length.toLocaleString('en-US')}-package list.`,
    `- ${viaDownloads} of the listed overrides qualify through download volume (their`,
    '  `npmHighImpact` rank equals their `npmTopDownloads` rank);',
    `  ${inDependents.length} also chart in \`npmTopDependents\`.`,
    `- The highest-impact override is \`${highest?.name ?? '?'}\` at rank ${highest?.impactRank ?? '?'} - the top`,
    `  ${highestPct}% of the list.`,
    '',
    '## Top 15 by dependent count',
    '',
    `Dependent rank is position in \`npmTopDependents\` (${data.npmTopDependents.length.toLocaleString('en-US')} packages).`,
    '',
    '| Dependents rank | Package | Impact rank |',
    '| ---: | --- | ---: |',
    ...byDependents
      .slice(0, 15)
      .map(
        r =>
          `| ${formatCell(r.dependentsRank)} | \`${r.name}\` | ${formatCell(r.impactRank)} |`,
      ),
    '',
    `## All ${listed.length} listed overrides`,
    '',
    'Sorted by `npmHighImpact` rank. A dash means the package does not chart',
    'in `npmTopDependents`.',
    '',
    '| Impact rank | Package | Dependents rank |',
    '| ---: | --- | ---: |',
    ...listed.map(
      r =>
        `| ${formatCell(r.impactRank)} | \`${r.name}\` | ${formatCell(r.dependentsRank)} |`,
    ),
    '',
  ]
  return lines.join('\n')
}

export function readOverrideUpstreamNames(): string[] {
  return readdirSync(NPM_PACKAGES_PATH)
    .toSorted()
    .map(dir => resolveOriginalPackageName(dir))
}

async function main(): Promise<void> {
  const data = await loadHighImpactData()
  const doc = renderHighImpactRankings(data, readOverrideUpstreamNames())
  if (process.argv.includes('--write')) {
    writeFileSync(RANKINGS_DOC_PATH, doc)
    logger.success(
      `gen-high-impact-rankings: wrote ${path.relative(ROOT_PATH, RANKINGS_DOC_PATH)} from npm-high-impact ${data.version}.`,
    )
    return
  }
  process.stdout.write(doc)
}

/* c8 ignore start - entrypoint guard; the pure legs are covered directly. */
if (isMainModule(import.meta.url)) {
  main().catch((e: unknown) => {
    logger.fail(`gen-high-impact-rankings failed: ${String(e)}`)
    process.exitCode = 1
  })
}
/* c8 ignore stop */
