name: ⚙️ Linting

# Dependencies:
#   - SocketDev/socket-registry/.github/workflows/lint.yml@main

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-check:
    uses: SocketDev/socket-registry/.github/workflows/lint.yml@main
    with:
      setup-script: 'pnpm run build'
