name: ⚙️ Socket Fix Auto Pull Request

# Dependencies:
#   - SocketDev/socket-registry/.github/workflows/socket-auto-pr.yml

on:
  schedule:
    - cron: '0 0 * * *'   # Run daily at midnight UTC
    - cron: '0 12 * * *'  # Run daily at noon UTC
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug output'
        required: false
        default: '0'
        type: string
        options:
          - '0'
          - '1'

permissions:
  contents: write
  pull-requests: write

jobs:
  socket-auto-pr:
    uses: SocketDev/socket-registry/.github/workflows/socket-auto-pr.yml@1f4ae0df40e5d4e506e9155db9c3c6a77864fdcc # main
    with:
      debug: ${{ inputs.debug }}
      autopilot: true
    secrets:
      socket_cli_api_token: ${{ secrets.SOCKET_CLI_API_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
